// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.23.3
// source: api/order/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrderGetUserByOrderId = "/api.order.v1.Order/GetUserByOrderId"

type OrderHTTPServer interface {
	GetUserByOrderId(context.Context, *GetUserByOrderIdRequest) (*GetUserByOrderIdReply, error)
}

func RegisterOrderHTTPServer(s *http.Server, srv OrderHTTPServer) {
	r := s.Route("/")
	r.GET("/order/getUser/{id}", _Order_GetUserByOrderId0_HTTP_Handler(srv))
}

func _Order_GetUserByOrderId0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserByOrderIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetUserByOrderId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserByOrderId(ctx, req.(*GetUserByOrderIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserByOrderIdReply)
		return ctx.Result(200, reply)
	}
}

type OrderHTTPClient interface {
	GetUserByOrderId(ctx context.Context, req *GetUserByOrderIdRequest, opts ...http.CallOption) (rsp *GetUserByOrderIdReply, err error)
}

type OrderHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderHTTPClient(client *http.Client) OrderHTTPClient {
	return &OrderHTTPClientImpl{client}
}

func (c *OrderHTTPClientImpl) GetUserByOrderId(ctx context.Context, in *GetUserByOrderIdRequest, opts ...http.CallOption) (*GetUserByOrderIdReply, error) {
	var out GetUserByOrderIdReply
	pattern := "/order/getUser/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderGetUserByOrderId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
